// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackWard: typeof import('./src/components/Header/Sub/BackWard.vue')['default']
    Base: typeof import('./src/components/Container/Home/Card/Base.vue')['default']
    CitySelector: typeof import('./src/components/Header/Sub/CitySelector.vue')['default']
    Common: typeof import('./src/components/Header/Common.vue')['default']
    FalseInput: typeof import('./src/components/Header/Sub/FalseInput.vue')['default']
    Home: typeof import('./src/components/Header/Home.vue')['default']
    Index: typeof import('./src/components/SearchInput/Index.vue')['default']
    Rate: typeof import('./src/components/Container/Common/Rate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sub: typeof import('./src/components/Tab/Sub.vue')['default']
  }
}

export {}
